name = "Autohctsa"
uuid = "10eb88ab-3e11-4490-b92e-b8fb5c85de83"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com>"]
version = "0.1.0"

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
